app/sisevento/urls.py
from __future__ import unicode_literals
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'sisevento'

urlpatterns = [

	path ('', views.Home.as_view(), name='home'), 

	path ('cadastro/', views.UserCreateView.as_view(), name='cadastro'),

	path ('atividade/', views.Atividade.as_view(), name='atividade'),

	path ('veratividade/', views.Veratividade.as_view(), name='veratividade'),

	path ('eventos/', views.Eventos.as_view(), name='eventos'),

	path ('listareventos/', views.ListEvento.as_view(), name='listareventos'),

	path ('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

	path ('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.sisevento.urls'), name='sisevento'),
]

app/sisevento/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import uuid
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser, Group, Permission

# CreateUpdateModel
# - - - - - - - - - - - - - - - - - - -
class CreateUpdateModel(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now=True)

    class Meta:
        abstract = True


# UUIDUser
# - - - - - - - - - - - - - - - - - - -
class UUIDUser(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    groups = models.ManyToManyField(Group, blank=True, related_name="uuiduser_set", related_query_name="user")
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name="uuiduser_set", related_query_name="user")

    # core
    cpf = models.IntegerField(verbose_name="CPF")
    telefone = models.IntegerField(verbose_name="telefone")


    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'usuário'
        verbose_name_plural = 'usuários'

class Atividade(models.Model):
    types = (
    (1, 'Palestra'),
    (2, 'Minicurso')
)
    nomeatividade = models.CharField (max_length = 100, verbose_name='Nome da Atividade')
    criador = models.ForeignKey (UUIDUser, on_delete = models.CASCADE, related_name='atividade', verbose_name='criador')
    palestrante = models.CharField (max_length = 100, verbose_name='Criador')
    duracao = models.CharField (max_length = 100, verbose_name='Duração')
    data = models.DateTimeField (auto_now = False, auto_now_add = False)
    tipo = models.IntegerField (choices = types)

    def __str__(self):
        return self.nomeatividade

class Eventos (models.Model):
    criador = models.ForeignKey (UUIDUser, on_delete = models.CASCADE, related_name='eventos', verbose_name='criador')
    atividade = models.ForeignKey (Atividade, on_delete = models.CASCADE, related_name='eventos', verbose_name='atividade')
    descricao = models.TextField (verbose_name='Descricao')
    nome = models.CharField (max_length = 100, verbose_name='Nome')

app/sisevento/forms.py
#coding:utf-8

from __future__ import unicode_literals
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import UUIDUser, Atividade, Eventos

# User: create
# - - - - - - - - - - - - - - - - - - -
class UUIDUserForm(forms.ModelForm):
    class Meta:
        model = UUIDUser
        fields = ('username', 'password', 'email', 'cpf', 'telefone')
        labels = {
        'username': 'Nome de Usuário',
        'password': 'Senha',
        'email': 'Email',
        'cpf': 'CPF',
        'telefone': 'Telefone',
    }
        widgets={
            'password': forms.PasswordInput()
}

class Atividade (forms.ModelForm): 
    class Meta: 
        model = Atividade
        fields  = ('nomeatividade', 'palestrante', 'duracao', 'data', 'tipo')
        labels = {
        'nomeatividade': 'Nome da Atividade',
        'palestrante': 'Palestrante',
        'duracao': 'Duração',
        'data': 'Data',
        'tipo': 'Tipo',
    }

class Evento(forms.ModelForm): 
    class Meta: 
        model = Eventos
        fields  = ('atividade', 'descricao', 'nome')
        labels = {
        'atividade': 'Atividade',
        'descricao': 'Descrição',
        'nome': 'Nome',
    }

app/sisevento/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models
from .forms import UUIDUserForm, Atividade, Evento
class UserCreateView(CreateView):
    model = models.UUIDUser
    template_name = 'cadastrouser.html'
    success_url = reverse_lazy('sisevento:login')
    form_class = UUIDUserForm
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.set_password(obj.password)
        obj.save()
        return super(UserCreateView, self).form_valid(form)

class Home (TemplateView):
	template_name = 'home.html'

class Atividade(CreateView):
    model = models.Atividade
    template_name = 'atividade.html'
    success_url = reverse_lazy('sisevento:home')
    form_class = Atividade
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.criador = self.request.user 
        obj.save()
        return super(Atividade, self).form_valid(form)

class Veratividade(ListView):
    model = models.Atividade
    template_name = 'veratividade.html'

class Eventos(CreateView):
    model = models.Eventos
    template_name = 'eventos.html'
    success_url = reverse_lazy('sisevento:home')
    form_class = Evento
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.criador = self.request.user 
        obj.save()
        return super(Eventos, self).form_valid(form)

class ListEvento (ListView):
    model = models.Eventos
    template_name = 'listareventos.html'

templates/atividade.html
<!DOCTYPE html>
<html>
<head>
	<title>Atividade</title>
</head>
<body>
<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Salvar"/>
	</form>
</body>
</html>

templates/cadastrouser.html
<!DOCTYPE html>
<html>
<head>
	<title>Cadastro</title>
</head>
<body>
<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Cadastrar"/>
	</form>
</body>
</html>

templates/eventos.html
<!DOCTYPE html>
<html>
<head>
	<title>Eventos</title>
</head>
<body>
<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Eventos"/>
	</form>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title> Sistema de Vendas </title>
</head>
<body>
	{%if user.is_authenticated %}
		<a href="{% url 'sisevento:atividade' %}"> Criar Atividade </a>
		<a href="{% url 'sisevento:veratividade' %}"> Ver Atividade </a>
		<a href="{% url 'sisevento:eventos' %}"> Criar Eventos </a>
		<a href="{% url 'sisevento:listareventos' %}"> Listar Eventos </a>
		<a href="{% url 'sisevento:logout' %}"> Sair </a>
	{% else %}
		<a href="{% url 'sisevento:home' %}"> Home </a>
		<a href="{% url 'sisevento:cadastro' %}"> Cadastro </a>
		<a href="{% url 'sisevento:login' %}"> Login </a>
	{%endif%}

</body>
</html>

templates/listareventos.html
<!DOCTYPE html>
<html>
<head>
	<title>Listar Eventos</title>
</head>
<body>
{%for x in object_list%}
	{%if request.user == x.criador%}
		Decrição:
		<p>{{x.descricao}}</p>
		Nome:
		<p>{{x.nome}}</p>
		Atividade:
		<p>{{x.atividade}} </p>
	{%endif%}
{%endfor%}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>
<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Login"/>
	</form>
</body>
</html>

templates/veratividade.html
<!DOCTYPE html>
<html>
<head>
	<title>Ver atividade</title>
</head>
<body>
{%for x in object_list%}
	{%if request.user == x.criador%}
		{{x.palestrante}}
		{{x.duracao}}
		{{x.data}}
		{{x.tipo}} 
	{%endif%}
{%endfor%}
</body>
</html>